export const canadianProvinceOptions = [
  { value: "AB", label: "Alberta" },
  { value: "BC", label: "British Columbia" },
  { value: "MB", label: "Manitoba" },
  { value: "NB", label: "New Brunswick" },
  { value: "NL", label: "Newfoundland and Labrador" },
  { value: "NS", label: "Nova Scotia" },
  { value: "NT", label: "Northwest Territories" },
  { value: "NU", label: "Nunavut" },
  { value: "ON", label: "Ontario" },
  { value: "PE", label: "Prince Edward Island" },
  { value: "QC", label: "Quebec" },
  { value: "SK", label: "Saskatchewan" },
  { value: "YT", label: "Yukon" },
];

export const commonOntarioCities = [
  "Toronto",
  "Etobicoke",
  "Mississauga",
  "Oakville",
  "Burlington",
  "Hamilton",
  "Ancaster",
  "Dundas",
  "Scarborough",
  "North York",
  "Vaughan",
  "Markham",
  "Richmond Hill",
  "Brampton",
  "Ajax",
  "Pickering",
  "Whitby",
  "Oshawa",
  "Kitchener",
  "Waterloo",
];

export const ontarioRegionOptions = [
  {
    value: "greater-toronto-area",
    label: "Greater Toronto Area",
    cities: [
      "Toronto",
      "Etobicoke",
      "Scarborough",
      "North York",
      "Mississauga",
      "Brampton",
      "Vaughan",
      "Markham",
      "Richmond Hill",
      "Oakville",
      "Pickering",
      "Ajax",
      "Whitby",
      "Oshawa",
    ],
  },
  {
    value: "hamilton-halton-niagara",
    label: "Hamilton, Halton, Niagara",
    cities: [
      "Hamilton",
      "Ancaster",
      "Dundas",
      "Burlington",
      "Milton",
      "Halton Hills",
      "Grimsby",
      "St. Catharines",
      "Niagara Falls",
      "Welland",
    ],
  },
  {
    value: "waterloo-wellington",
    label: "Waterloo, Wellington, Guelph",
    cities: ["Kitchener", "Waterloo", "Cambridge", "Guelph", "Woolwich", "Wilmot", "Wellesley", "Fergus", "Elora"],
  },
  {
    value: "london-southwestern",
    label: "London and Southwestern Ontario",
    cities: ["London", "St. Thomas", "Woodstock", "Stratford", "Ingersoll", "Sarnia", "Chatham", "Windsor"],
  },
  {
    value: "ottawa-eastern",
    label: "Ottawa and Eastern Ontario",
    cities: [
      "Ottawa",
      "Orleans",
      "Kanata",
      "Nepean",
      "Gatineau",
      "Arnprior",
      "Carleton Place",
      "Kingston",
      "Brockville",
      "Cornwall",
    ],
  },
  {
    value: "central-ontario",
    label: "Central Ontario",
    cities: ["Barrie", "Orillia", "Innisfil", "Newmarket", "Aurora", "Bradford West Gwillimbury", "Collingwood", "Midland"],
  },
  {
    value: "other-ontario",
    label: "Other Ontario",
    cities: ["Other"],
  },
];

export const serviceRadiusOptions = [25, 50, 75, 100, 150, 200];

export const strongLeadFactorOptions = [
  "Clear project description",
  "Realistic budget",
  "Matches preferred work",
  "Useful timeline context",
  "Photos available",
  "Complete contact details",
  "Decision maker is involved",
  "Scope is appropriate for my crew",
  "Other",
];
