import { defaultProjectTypes } from "./projectOptions";
import type { ClientConfig } from "@/lib/types";

export const demoClients: ClientConfig[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    businessName: "Northline Design Build",
    slug: "northline-design-build",
    brandColor: "#4d6b58",
    notificationEmail: "owner+northline@example.com",
    phone: "416-555-0141",
    websiteUrl: "https://example.com/northline",
    serviceArea: "Toronto west end and Etobicoke",
    businessRegion: "greater-toronto-area",
    businessCity: "Toronto",
    businessProvince: "ON",
    businessPostalCode: "M6P",
    serviceRadiusKm: 75,
    projectTypes: defaultProjectTypes,
    leadFitCriteria:
      "A strong lead has a clear project description, realistic budget for the requested work, useful timeline context, at least one reliable contact method, and enough detail to decide whether to follow up.",
    businessPreferences:
      "Prefers kitchen, bathroom, main-floor, and whole-home renovations. Smaller repair work is acceptable when it may lead to a larger relationship.",
    preferredProjectTypes: ["Kitchen renovation", "Bathroom renovation", "Main floor renovation", "Whole-home renovation"],
    strongLeadFactors: ["Clear project description", "Realistic budget", "Matches preferred work", "Useful timeline context"],
    isActive: true,
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    businessName: "Clearspace Basements",
    slug: "clearspace-basements",
    brandColor: "#345f7d",
    notificationEmail: "owner+clearspace@example.com",
    phone: "905-555-0172",
    websiteUrl: "https://example.com/clearspace",
    serviceArea: "Mississauga, Oakville, Burlington",
    businessRegion: "greater-toronto-area",
    businessCity: "Mississauga",
    businessProvince: "ON",
    businessPostalCode: "L5B",
    serviceRadiusKm: 75,
    projectTypes: defaultProjectTypes,
    leadFitCriteria:
      "A strong lead has a clear project description, realistic budget for the requested work, useful timeline context, at least one reliable contact method, and enough detail to decide whether to follow up.",
    businessPreferences:
      "Specializes in basement finishing, basement renovations, and lower-level living spaces. Kitchen or outdoor projects are usually lower priority.",
    preferredProjectTypes: ["Basement renovation", "Repairs or smaller updates"],
    strongLeadFactors: ["Clear project description", "Realistic budget", "Matches preferred work", "Complete contact details"],
    isActive: true,
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    businessName: "Prime Coat Painting",
    slug: "prime-coat-painting",
    brandColor: "#8a5a44",
    notificationEmail: "owner+primecoat@example.com",
    phone: "647-555-0118",
    websiteUrl: "https://example.com/primecoat",
    serviceArea: "Toronto, Scarborough, North York",
    businessRegion: "greater-toronto-area",
    businessCity: "Toronto",
    businessProvince: "ON",
    businessPostalCode: "M1P",
    serviceRadiusKm: 50,
    projectTypes: defaultProjectTypes,
    leadFitCriteria:
      "A strong lead has a clear project description, realistic budget for the requested work, useful timeline context, at least one reliable contact method, and enough detail to decide whether to follow up.",
    businessPreferences:
      "Prefers painting, finishing, drywall repair, trim, and refresh projects. Large structural renovation work is usually not ideal.",
    preferredProjectTypes: ["Painting or finishing", "Repairs or smaller updates"],
    strongLeadFactors: ["Clear project description", "Realistic budget", "Matches preferred work", "Photos available"],
    isActive: true,
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    businessName: "Cedar & Stone Outdoor",
    slug: "cedar-stone-outdoor",
    brandColor: "#6f7f45",
    notificationEmail: "owner+cedarstone@example.com",
    phone: "289-555-0157",
    websiteUrl: "https://example.com/cedarstone",
    serviceArea: "Hamilton, Ancaster, Dundas",
    businessRegion: "hamilton-halton-niagara",
    businessCity: "Hamilton",
    businessProvince: "ON",
    businessPostalCode: "L8P",
    serviceRadiusKm: 75,
    projectTypes: defaultProjectTypes,
    leadFitCriteria:
      "A strong lead has a clear project description, realistic budget for the requested work, useful timeline context, at least one reliable contact method, and enough detail to decide whether to follow up.",
    businessPreferences:
      "Prefers decks, patios, outdoor living spaces, fencing, and landscape-adjacent carpentry. Interior renovation work is not the main focus.",
    preferredProjectTypes: ["Deck or outdoor living space", "Repairs or smaller updates", "Other"],
    strongLeadFactors: ["Clear project description", "Realistic budget", "Matches preferred work", "Useful timeline context"],
    isActive: true,
  },
];
